//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 05:43:32 PM CET 
//


package pl.coderstrust.service.soap.bindingClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoicesList" type="{http://invoiceapp-service.com}invoicesList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicesList"
})
@XmlRootElement(name = "getInvoicesByDateResponse")
public class GetInvoicesByDateResponse {

    @XmlElement(required = true)
    protected InvoicesList invoicesList;

    /**
     * Gets the value of the invoicesList property.
     * 
     * @return
     *     possible object is
     *     {@link InvoicesList }
     *     
     */
    public InvoicesList getInvoicesList() {
        return invoicesList;
    }

    /**
     * Sets the value of the invoicesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoicesList }
     *     
     */
    public void setInvoicesList(InvoicesList value) {
        this.invoicesList = value;
    }

}
