//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.10 at 08:44:55 PM CET 
//


package pl.coderstrust.service.soap.bindingClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoice" type="{http://invoiceapp-service.com}invoice"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoice"
})
@XmlRootElement(name = "getInvoiceByIdResponse")
public class GetInvoiceByIdResponse {

  @XmlElement(required = true)
  protected Invoice invoice;

  /**
   * Gets the value of the invoice property.
   *
   * @return possible object is {@link Invoice }
   */
  public Invoice getInvoice() {
    return invoice;
  }

  /**
   * Sets the value of the invoice property.
   *
   * @param value allowed object is {@link Invoice }
   */
  public void setInvoice(Invoice value) {
    this.invoice = value;
  }

}
