//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.10 at 08:44:55 PM CET 
//


package pl.coderstrust.service.soap.bindingClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the pl.coderstrust.service.soap.bindingClasses package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation for XML content. The Java representation of
 * XML content can consist of schema derived interfaces and classes representing the binding of
 * schema type definitions, element declarations and model groups.  Factory methods for each of
 * these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: pl.coderstrust.service.soap.bindingClasses
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link DeleteInvoiceByIdRequest }
   */
  public DeleteInvoiceByIdRequest createDeleteInvoiceByIdRequest() {
    return new DeleteInvoiceByIdRequest();
  }

  /**
   * Create an instance of {@link SaveInvoiceRequest }
   */
  public SaveInvoiceRequest createSaveInvoiceRequest() {
    return new SaveInvoiceRequest();
  }

  /**
   * Create an instance of {@link Invoice }
   */
  public Invoice createInvoice() {
    return new Invoice();
  }

  /**
   * Create an instance of {@link GetInvoicesBySellerResponse }
   */
  public GetInvoicesBySellerResponse createGetInvoicesBySellerResponse() {
    return new GetInvoicesBySellerResponse();
  }

  /**
   * Create an instance of {@link InvoicesList }
   */
  public InvoicesList createInvoicesList() {
    return new InvoicesList();
  }

  /**
   * Create an instance of {@link GetInvoicesRequest }
   */
  public GetInvoicesRequest createGetInvoicesRequest() {
    return new GetInvoicesRequest();
  }

  /**
   * Create an instance of {@link GetInvoicesResponse }
   */
  public GetInvoicesResponse createGetInvoicesResponse() {
    return new GetInvoicesResponse();
  }

  /**
   * Create an instance of {@link GetInvoicesByDateResponse }
   */
  public GetInvoicesByDateResponse createGetInvoicesByDateResponse() {
    return new GetInvoicesByDateResponse();
  }

  /**
   * Create an instance of {@link SaveInvoiceResponse }
   */
  public SaveInvoiceResponse createSaveInvoiceResponse() {
    return new SaveInvoiceResponse();
  }

  /**
   * Create an instance of {@link DeleteInvoiceByIdResponse }
   */
  public DeleteInvoiceByIdResponse createDeleteInvoiceByIdResponse() {
    return new DeleteInvoiceByIdResponse();
  }

  /**
   * Create an instance of {@link GetInvoiceByIdResponse }
   */
  public GetInvoiceByIdResponse createGetInvoiceByIdResponse() {
    return new GetInvoiceByIdResponse();
  }

  /**
   * Create an instance of {@link GetInvoicesByBuyerResponse }
   */
  public GetInvoicesByBuyerResponse createGetInvoicesByBuyerResponse() {
    return new GetInvoicesByBuyerResponse();
  }

  /**
   * Create an instance of {@link GetInvoiceByIdRequest }
   */
  public GetInvoiceByIdRequest createGetInvoiceByIdRequest() {
    return new GetInvoiceByIdRequest();
  }

  /**
   * Create an instance of {@link GetInvoicesBySellerRequest }
   */
  public GetInvoicesBySellerRequest createGetInvoicesBySellerRequest() {
    return new GetInvoicesBySellerRequest();
  }

  /**
   * Create an instance of {@link GetInvoicesByDateRequest }
   */
  public GetInvoicesByDateRequest createGetInvoicesByDateRequest() {
    return new GetInvoicesByDateRequest();
  }

  /**
   * Create an instance of {@link GetInvoicesByBuyerRequest }
   */
  public GetInvoicesByBuyerRequest createGetInvoicesByBuyerRequest() {
    return new GetInvoicesByBuyerRequest();
  }

  /**
   * Create an instance of {@link InvoiceEntry }
   */
  public InvoiceEntry createInvoiceEntry() {
    return new InvoiceEntry();
  }

  /**
   * Create an instance of {@link Address }
   */
  public Address createAddress() {
    return new Address();
  }

  /**
   * Create an instance of {@link Company }
   */
  public Company createCompany() {
    return new Company();
  }

}
